/**
 * Asset-drift guard for the bundled bunker-marker PNGs
 * (specs/lettered-bunker-legend-plan.md Step 7 #5).
 *
 * Catches "edited generate-bunker-marker.py, forgot to re-run/commit the
 * PNGs" — verifies the 7 expected files exist, are valid PNGs, and are the
 * expected 96x96 canvas size. `node:fs`/`node:path` only, no image library,
 * no new deps.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ASSETS_DIR = join(__dirname, '..', '..', '..', 'public', 'assets');

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

const EXPECTED_FILES = [
  'bunker-marker.png',
  'bunker-marker-a.png',
  'bunker-marker-b.png',
  'bunker-marker-c.png',
  'bunker-marker-d.png',
  'bunker-marker-e.png',
  'bunker-marker-f.png',
];

describe('bundled bunker-marker PNGs — generated by scripts/generate-bunker-marker.py', () => {
  for (const filename of EXPECTED_FILES) {
    describe(filename, () => {
      const path = join(ASSETS_DIR, filename);

      it('exists', () => {
        expect(existsSync(path)).toBe(true);
      });

      it('starts with the PNG signature and has a 96x96 IHDR', () => {
        const buf = readFileSync(path);
        expect(buf.subarray(0, 8).equals(PNG_SIGNATURE)).toBe(true);

        // IHDR chunk: bytes 8-15 = length(4)+"IHDR"(4); width = bytes 16-19 (BE),
        // height = bytes 20-23 (BE).
        const width = buf.readUInt32BE(16);
        const height = buf.readUInt32BE(20);
        expect(width).toBe(96);
        expect(height).toBe(96);
      });
    });
  }
});
